### ISSUE TITLE
Solution for Cannot create/start proxy container

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/docs#54]
Issues like: https://community.easyengine.io/t/cannot-create-start-proxy-container-please-make-sure-port-80-and-443-are-free-only-2-sites-are-on-server/11818 got reported after `EasyEngine v4.0.8` update. Which switched to using global-services with docker-compose generated names post this update.

This issue is very specific on to docker-compose version `1.23.0` and `1.23.1`, [version 1.23.0](https://github.com/docker/compose/releases/tag/1.23.0) had a naming scheme update: the old scheme `project>_<service>_<index>` was updated to
`<project>_<service>_<index>_<slug>`, where `<slug>` is a randomly-generated
hexadecimal string.

This change is present for people who had installed EasyEngine between 31st October 2018 to 29th November 2018. Which crosses over with the time line of `rc` and stable release. 

**On 29th November this change was reverted back in [docker-compose version 1.23.2](https://github.com/docker/compose/releases/tag/1.23.2).**

A blogpost needs to written stating this issue and manual steps to resolve them need to be give. Due to this no existing sites got affected, only creation of new sites got hampered.

#### Steps to resolve this issue: (To be provided in blog for users):

1. Update docker-compose to latest version.
```bash
sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

2. Restart global-services:
```bash
cd /opt/easyengine/services && \
docker-compose down && \
docker-compose up -d 
```

3. Restart sites:
```bash
for site in $(ee site list --format=text); do ee site disable $site && ee site enable $site; done
```

New site creation should start after this.

**Comment by kirtangajjar** [comment]
Article published - https://easyengine.io/handbook/solution-for-cannot-create-start-proxy-container
